### ISSUE TITLE
ParseError expected ":", got "."

### ISSUE THREAD

**Issue by marcobarbosa** [blakeembrey/stylus-type-utils#4]
Hi,

I'm trying to use your package. I have installed version 0.0.3. Using Node 5.0.0.

Doing a `@import 'stylus-type-utils'` throws:

```
ParseError: node_modules/stylus-type-utils/lib/type-utils.js:5:11
   1| var plugin = module.exports = function plugin () {
   2|   'use strict';
   3|
   4|   return function (style) {
   5|     style.include(__dirname);
----------------^
   6|     style.import('type-utils');
   7|   };
   8| };

expected ":", got "."
```

**Comment by blakeembrey** [comment]
What version of Sylus? I haven't work with Stylus in a long time now, but it looks like they made a change to how imports are being resolved and now it's trying to import a JavaScript file?

**Comment by blakeembrey** [comment]
Could you try tweaking the imports to find the issue? If you change the import in `index.styl` to be explicit to the two files instead of to the folder, does that work?

**Comment by marcobarbosa** [comment]
Stylus version **0.54.2**. I've tried tweaking the `index.styl`and the only way to get away with the error is to comment `@import styles-type-utils`. If you have any other ideas I'd be happy to try,

**Comment by blakeembrey** [comment]
Just got around to testing it, works according to the README. Use `import "node_modules/stylus_type_utils" or `stylus -u stylus-type-utils` with `@import "type-utils"`.
